name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up SSH agent and add the private key from secrets
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      
      - name: Kill old process if necessary
        run: |
          ssh -o StrictHostKeyChecking=no rmaptbu@34.69.180.97 << 'EOF'
          if pgrep server.x86_64 > /dev/null
          then
            echo "Stopping running process..."
            pkill -f /usr/local/bin/server.x86_64  
          else
            echo "Process is not running."
          fi
          EOF
          
      # Copy the subfolder to the GCE instance
      - name: Move files over
        run: |
          scp -r -o StrictHostKeyChecking=no ./build/linux/*   rmaptbu@34.69.180.97:/usr/local/bin/
      - name: Start server
        run: |
          ssh -o StrictHostKeyChecking=no rmaptbu@34.69.180.97 << 'EOF' 
          chmod +x /usr/local/bin/server.x86_64
          nohup /usr/local/bin/server.x86_64 --headless &> /usr/local/bin/output.log &
          echo "process restarted"
          EOF
