name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up SSH agent and add the private key from secrets
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Copy the subfolder to the GCE instance
      - name: Copy files and start server
        run: |
          ssh -o StrictHostKeyChecking=no rmaptbu@34.69.180.97 "killall /usr/local/bin/server.x86_64"
          scp -r -o StrictHostKeyChecking=no ./build/linux/*   rmaptbu@34.69.180.97:/usr/local/bin/
          ssh -o StrictHostKeyChecking=no rmaptbu@34.69.180.97 "chmod +x /usr/local/bin/server.x86_64"
          ssh -o StrictHostKeyChecking=no rmaptbu@34.69.180.97 "nohup /usr/local/bin/server.x86_64 --headless &> /usr/local/bin/output.log &"
