name: Deploy to GCE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up SSH agent and add the private key from secrets
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Copy the subfolder to the GCE instance
      - name: Copy subfolder to GCE
        run: |
          scp -r -o StrictHostKeyChecking=no ./build/linux/ rmaptbu@34.69.180.97:/bin/

      # Run a command on the GCE instance
      # - name: Run command on GCE instance
      #   run: |
      #     ssh -o StrictHostKeyChecking=no rmaptbu@34.69.180.97 "cd /bin/ && ./your_command.sh"
